### ISSUE TITLE
OCL_ICD_VENDORS doesn't work if there's no / at the end

### ISSUE THREAD

**Issue by isuruf** [KhronosGroup/OpenCL-ICD-Loader#104] opened 2020-04-11 17:32 UTC
The README.md file has the example,

```
export OCL_ICD_VENDORS=/my/local/icd/search/path
```
but this should be,
```
export OCL_ICD_VENDORS=/my/local/icd/search/path/
```

Or I could fix https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/master/loader/linux/icd_linux.c#L87-L93 to add a `/` at the end.

**Comment by alycm** [comment] 2020-04-11 21:16
Hello, thank you for the bug report.

Not entirely helpful as it isn't merged, but I think that https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/91 fixes this issue?

**Comment by isuruf** [comment] 2020-04-11 21:21
Thanks.

**Comment by alycm** [comment] 2020-04-11 21:28
I've reopened this issue as until that PR is merged the issue isn't fixed.

**Comment by bashbaug** [comment] 2020-04-16 06:17
I just merged #91.  If that is sufficient then I think we can close this issue.  Thanks!

**Comment by isuruf** [comment] 2020-04-16 12:29
Yes, it is enough. Thanks

**Comment by bashbaug** [comment] 2020-04-20 18:12
> Yes, it is enough. Thanks

Great, thank!  Closing.

**Closed by bashbaug** 2020-04-20 18:12 UTC
