### ISSUE TITLE
Runtime errors from wrong vendor library

### ISSUE THREAD

**Issue by josephnoir** [KhronosGroup/OpenCL-ICD-Loader#12] opened 2017-03-20 12:14 UTC
Running OpenCL programs on a host that includes a Nvidia Tesla GPU as well as a Intel Xeon Phi sometimes leads to an error that looks like it originates from the wrong vendor library.

Specifically, executing a program on the Tesla GPU lead to an error expected from the Xeon Phi coprocessor. The error message included `HARDWARE FAULT MIC ` (or something similar) in the name, which hints at the Xeon Phi, also named Many Integrated Core device and registered as `mic` under `/dev`.

Removing the Intel ICD from the `/etc/OpenCL/vendors/` directory prevented the error from occurring again. However, this prevents dynamic device selection at runtime.

The host is a Linux server running CentOS with the latest available NVIDIA driver and the older Intel OpenCL driver that works for the Xeon Phi. The OpenCL library placed in `/etc/lib64` is built from this repository and tested as described in the README.

**Comment by kepatil** [comment] 2017-03-20 14:40
Hi Joseph,

I need more details to understand this better. I am assuming that "executing a program" means calling clEnqueueNDRangeKernel.

* Where do you see the error? Is it in dmesg output? Can you provide the full error string?
* How often do you see this error?
* Can you provide sample code that reproduces the issue?

The ICD Loader dispatches calls to one of the installed vendor implementations by means of a function pointer table present inside an OpenCL object. In case of clEnqueueNDRangeKernel it will be the command queue passed to it as the first argument. When the error ocurrs, can you verify that the command queue that was passed was created on the intended device (the Tesla GPU in your case)?

**Comment by josephnoir** [comment] 2017-03-20 15:02
Hi Kedar,

yes, by executing I mean calling `clEnqueueNDRangeKernel`, sorry for the inaccuracy.

I got some test running on the Tesla right now, but I'll try to recreate the error after that and post a log. My use case right now is a radix sort as part of larger algorithm. Maybe, extracting the sort will be enough to provide a smaller sample to reproduce the error. The error doesn't occur each time and is printed to the terminal.

The command queue should be associated with the Tesla GPU as querying the device name during setup returns the expected name. Moreover, I am using the code on different hosts where it works as expected. Admittedly, this is the only host that has multiple vendors.

**Comment by josephnoir** [comment] 2017-03-27 08:53
Hello,

took me while, but here is the exception:

```
*** OPENCL MIC DEVICE HW EXCEPTION ***: Segmentation fault (Address not mapped to object [0x7f7d7d7f5a08])

BACKTRACE:
/tmp/coi_procs/1/215487/mic_server[0x4076b2]
/lib64/libpthread.so.0(+0x105a0)[0x7f7edc30d5a0]
/lib64/libpthread.so.0(pthread_detach+0x36)[0x7f7edc305466]
/tmp/coi_procs/1/215487/libtbb_preview.so.2(_ZN3rml8internal14thread_monitor13detach_threadEm+0x6)[0x7f7edc52c3d6]
/tmp/coi_procs/1/215487/libtbb_preview.so.2(+0x12793)[0x7f7edc52c793]
/tmp/coi_procs/1/215487/libtbb_preview.so.2(+0x181dc)[0x7f7edc5321dc]
/tmp/coi_procs/1/215487/libtbb_preview.so.2(+0x14eff)[0x7f7edc52eeff]
/tmp/coi_procs/1/215487/mic_server[0x43f802]
/tmp/coi_procs/1/215487/mic_server[0x40c92e]
/tmp/coi_procs/1/215487/mic_server[0x40c811]
/tmp/coi_procs/1/215487/mic_server[0x40c7da]
/tmp/coi_procs/1/215487/mic_server[0x40c656]
/tmp/coi_procs/1/215487/mic_server(release_device+0x2c)[0x41964c]
/usr/lib64/libcoi_device.so.0(+0x36bb0)[0x7f7edcbc5bb0]
/usr/lib64/libcoi_device.so.0(+0x37039)[0x7f7edcbc6039]
/usr/lib64/libcoi_device.so.0(+0x37319)[0x7f7edcbc6319]
/lib64/libpthread.so.0(+0x7394)[0x7f7edc304394]
/lib64/libc.so.6(clone+0x6d)[0x7f7edb6a92cd]

******************

terminate called after throwing an instance of 'std::runtime_error'
  what():  Segmentation fault
```

The trace looks like it originates from the MIC driver (or server). I wasn't able to reproduce the error using just the sorting algorithm. My code is rather bulky and I am not sure it would be helpful to you. I am running [this program](https://github.com/josephnoir/indexing/blob/master/src/phases.cpp) which depends on [CAF](https://github.com/actor-framework/actor-framework) and the `topic/multi_phase_kernels` branch of the [OpenCL module](https://github.com/actor-framework/opencl).

Another potential error source is the library loaded with the icd or the icd itself. Removing the `nvidia.icd` and leaving only an `nvidia64.icd` and `intel64.icd` (both created by hand) seems to fix the problem--at least I didn't notice it again after cleaning up the icds.

Since creating new icds might have fixed the problem, I would argue to close the issue and I'll report back if I stumble upon the problem again.

**Comment by kepatil** [comment] 2017-03-27 10:51
Thanks Joseph. Since there is nothing I can do at this point I will close the issue as you suggested. Feel free to reopen when you have more information.

**Closed by kepatil** 2017-03-27 10:51 UTC
