### ISSUE TITLE
Broken handling of 32-bit apps/OS

### ISSUE THREAD

**Issue by jjulianoatnv** [KhronosGroup/OpenCL-ICD-Loader#25] opened 2017-11-16 21:45 UTC
Inspecting the OpenCL loader, I noticed that the commit
- https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/188be6047481ea3c0c2ba5a7583ee13c8c3b2333

introduced a loader bug when running a 32-bit application. An analogous bug was added to the Vulkan loader. The Vulkan bug was fixed by

- https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/266c90b0333c9ba0fa49f8a5198ef8a48a82566b

OpenCL needs a similar fix.

The problem can be seen by inspecting the following code from https://github.com/KhronosGroup/OpenCL-ICD-Loader/commit/188be6047481ea3c0c2ba5a7583ee13c8c3b2333#diff-cdc4e03135a98264f91c20e2919d407f:

```
#ifdef _WIN64
static const char OPENCL_REG_SUB_KEY[] = "OpenCLDriverName";
#else
static const char OPENCL_REG_SUB_KEY[] = "OpenCLDriverNameWow";
#endif
```

This does the wrong thing when running a 32-bit application on a 64-bit OS, and it does the wrong thing when running a 32-bit application on a 32-bit OS.

See the Vulkan commit cited above for an example of how to fix it.

**Comment by jjulianoatnv** [comment] 2017-11-16 21:50
In case it is relevant, the Vulkan loader change that introduced the same bug was https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/9beaa801945469eebaae6feb2cb3ac1f85cea292#diff-5b4e070f5ce5cbb7bd1dd11f689d50a8.

It was followed quickly by a couple bugfixes. I have not checked if OpenCL needs similar bugfixes, and I leave that as an exercise for the reader.

For reference, see these Vulkan bugfixes:
- https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/b69cb52f7c39c8f6faeed7e172f90c8c4f307043
- https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/5d74c0d5f69d4c2ce4107f11461837b6f5b6fabb
- https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/54698c46985f01861e8f11797978c4a6142358b2
- https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/266c90b0333c9ba0fa49f8a5198ef8a48a82566b
- https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/0e020f43bf58d2bdb1d5a491e4127845d1e2f501

**Comment by kepatil** [comment] 2017-11-17 15:25
@ofirc Can you take this up since you are the author of the original change?

**Comment by ofirc** [comment] 2017-11-19 10:13
@kepatil I am a bit puzzled.
When running a 32-bit application (regardless of the OS) one would use the OpenCL.dll with the OpenCLDriverNameWow embedded inside. When running a 64-bit application one would use the OpenCL.dll with the OpenCLDriverName embedded inside.
This is a compile-time constant not a runtime one.

What exactly is the bug here?

If you try to build the following 32-bit/64-bit application through VS
you will get errors per the build architecture bitness you are targeting.

The only source of problems is if you abuse the compilation by adding -D_WIN64 where not necessary.

I would love to see a reproducer for the aforementioned problem.

Note that we have seen 0 regressions in our Graphics Driver samples, conformance and benchmarks and we are running it against both 32-bit and 64-bit apps.

This is the hello-world application I was using.

// ConsoleApplication12.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

#ifdef _WIN64
#error "Entered _WIN64 branch"
#else
#error "Entered _WIN32 branch"
#endif

int main()
{
    return 0;
}

**Comment by kepatil** [comment] 2017-11-20 15:24
> When running a 32-bit application (regardless of the OS) one would use the OpenCL.dll with the OpenCLDriverNameWow embedded inside. When running a 64-bit application one would use the OpenCL.dll with the OpenCLDriverName embedded inside.
> This is a compile-time constant not a runtime one.

The issue is that the suffix/substring "WoW" is meaningful only when a 32-bit application is running in a 64-bit Windows OS. A 32-bit application running on a 32-bit OS uses non-WoW names. So it has to be partly a compile time and partly a run time decision.

The logic needs to be something like:
```
#ifdef _WIN64 // compiling 64-bit Windows app
    // Use OpenCLDriverName, no runtime check needed
#else // compiling 32-bit Windows app
    if (running on a 32-bit Windows OS) { // runtime check
        // Use OpenCLDriverName
    }
    else {
        // Use OpenCLDriverNameWoW
    }
#endif
```
This [thread on SE](https://stackoverflow.com/questions/949959/why-do-64-bit-dlls-go-to-system32-and-32-bit-dlls-to-syswow64-on-64-bit-windows) has some details about how this weirdness came to be.

**Comment by ofirc** [comment] 2017-11-20 15:28
I see, now it makes sense. I'll submit a patch to fix that.

Thanks!
- Ofir

**Comment by kepatil** [comment] 2017-11-20 15:54
Thanks @ofirc. While at it could you check if the Vulkan bugfixes mentioned in https://github.com/KhronosGroup/OpenCL-ICD-Loader/issues/25#issuecomment-345074005 apply to the OpenCL ICD loader too?

Assigning to myself for tracking, awaiting your patch.

**Comment by kepatil** [comment] 2017-11-20 15:54
More background for the record:

The older registry keys in HKLM do not have this issue because we use the same name (SOFTWARE\Khronos\OpenCL\Vendors) for both 32-bit and 64-bit ICD entries. The function RegOpenKeyExA does a [registry redirection](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384232(v=vs.85).aspx), automatically mapping HKLM\Software to its WoW64 view when 32-bit app was running on 64-bit Windows.

In the new scheme we are responsible for using the correct name and do not benefit from automatic redirection.

**Comment by kepatil** [comment] 2018-02-20 14:16
@ofirc Were you able to work on the patch?

**Comment by ofirc** [comment] 2018-02-20 17:32
@kepatil Yes, started working on it and I'll submit a patch by tomorrow or Thursday 02/20 tops. Sorry for the delay.

**Comment by ofirc** [comment] 2018-02-22 18:28
@kepatil see https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/28 :-)
Let me know what you think.

**Comment by kepatil** [comment] 2018-07-13 14:56
Closing as #28 was merged.

**Closed by kepatil** 2018-07-13 14:56 UTC
